//
//  CourseDetailsWorker.swift
//  AppCleanSwift
//
//  Created by Igor on 10.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class CourseDetailsWorker {
    func getImageFromNet(withURL url: URL?) -> Data? {
        NetworkManager.shared.fetchImage(url: url)
    }
    
    func getFavoriteStatus(for courseName: String) -> Bool {
        UserDefaultsManager.shared.getDataUD(courseName: courseName)
    }
    
    func setFavoriteStatus(for courseName: String, with status: Bool) {
        UserDefaultsManager.shared.saveDataUD(status: status, courseName: courseName)
    }
}
