//
//  CourseDetailsPresenter.swift
//  AppCleanSwift
//
//  Created by Igor on 10.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol CourseDetailsPresentationLogic {
    func presentCourseDetails(response: CourseDetails.ShowDetails.Response)
}

class CourseDetailsPresenter: CourseDetailsPresentationLogic {
    weak var viewController: CourseDetailsDisplayLogic?

    func presentCourseDetails(response: CourseDetails.ShowDetails.Response) {
        let courseName = response.courseName ?? "Course name is empty"
        let lessonsCount = "Number of lessons \(response.lessonsCount ?? 0)"
        let testsCount = "Number of tests \(response.testsCount ?? 0)"
        let imageData = response.imageData ?? Data()
        
        let viewModel = CourseDetails.ShowDetails.ViewModel(
            courseName: courseName,
            lessonsCount: lessonsCount,
            testsCount: testsCount,
            imageData: imageData,
            isFavorite: response.isFavotite
        )
        viewController?.displayCourseDetails(viewModel: viewModel)
    }
}
