//
//  CourseDetailsInteractor.swift
//  AppCleanSwift
//
//  Created by Igor on 10.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseDetailsBusinessLogic {
    func doSomething(request: CourseDetails.ShowDetails.Request)
}

protocol CourseDetailsDataStore {
    
}

class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    
    func doSomething(request: CourseDetails.ShowDetails.Request) {
        worker = CourseDetailsWorker()
        worker?.doSomeWork()
        
        let response = CourseDetails.ShowDetails.Response()
        presenter?.presentSomething(response: response)
    }
}
