//
//  CourseDetailsViewController.swift
//  AppCleanSwift
//
//  Created by Igor on 10.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseDetailsDisplayLogic: AnyObject {
    func displayCourseDetails(viewModel: CourseDetails.ShowDetails.ViewModel)
    func displayFavoriteStatus(viewModel: CourseDetails.SetFavoriteStatus.ViewModel)
}

class CourseDetailsViewController: UIViewController {
        
    @IBOutlet var courseImageView: UIImageView!
    @IBOutlet var lessonsCountLabel: UILabel!
    @IBOutlet var testsCountLabel: UILabel!
    @IBOutlet var likeButton: UIButton!
    
    var interactor: CourseDetailsBusinessLogic?
    var router: (NSObjectProtocol & CourseDetailsRoutingLogic & CourseDetailsDataPassing)?
    
    // Данная сцена отображается при переходе
    // В инициализаторах вызывается метод для сборки сцены
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        
        CourseDetailsConfigurator.shared.configure(with: self)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        CourseDetailsConfigurator.shared.configure(with: self)
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        passRequest()
    }
    
    @IBAction func likeButtonIsPressed(_ sender: Any) {
        interactor?.setFavoriteStatus()
    }
    
    private func passRequest() {
        interactor?.provideCourseDetails()
    }
    
}

extension CourseDetailsViewController: CourseDetailsDisplayLogic {
    func displayCourseDetails(viewModel: CourseDetails.ShowDetails.ViewModel) {
        title = viewModel.courseName
        lessonsCountLabel.text = viewModel.lessonsCount
        testsCountLabel.text = viewModel.testsCount
        courseImageView.image = UIImage(data: viewModel.imageData)
        
        likeButton.tintColor = viewModel.isFavorite ? .red : .gray
    }
    
    func displayFavoriteStatus(viewModel: CourseDetails.SetFavoriteStatus.ViewModel) {
        likeButton.tintColor = viewModel.isFavorite ? .red : .gray
    }
}
