//
//  CourseDetailsInteractor.swift
//  AppCleanSwift
//
//  Created by Igor on 10.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseDetailsBusinessLogic {
    var isFavorite: Bool { get }
    func provideCourseDetails(request: CourseDetails.ShowDetails.Request)
}

// свойства для хранения данных, которые нужно подготавливать для передачи в Presenter
protocol CourseDetailsDataStore {
    var course: Course? { get }
}

class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    var course: Course?
    var isFavorite: Bool = false
    
    func provideCourseDetails(request: CourseDetails.ShowDetails.Request) {
        course = request.course
        worker = CourseDetailsWorker()
        
        isFavorite = worker?.getFavoriteStatus(for: course?.name ?? "") ?? false
        let imageData = worker?.getImageFromNet(withURL: course?.imageUrl)
        
        let response = CourseDetails.ShowDetails.Response(
            courseName: course?.name,
            lessonsCount: course?.numberOfLessons,
            testsCount: course?.numberOfTests,
            imageData: imageData,
            isFavotite: isFavorite
        )
        
        presenter?.presentCourseDetails(response: response)
    }
}
