//
//  CourseListInteractor.swift
//  AppCleanSwift
//
//  Created by Igor on 11.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseListBusinessLogic {
    func fetchCourses()
}

protocol CourseListDataStore {
    var courses: [Course] { get }
}

class CourseListInteractor: CourseListBusinessLogic, CourseListDataStore {
    
    var presenter: CourseListPresentationLogic?
    var worker: CourseListWorker?
    
    var courses: [Course] = []
    
    func fetchCourses() {
        NetworkManager.shared.fetchCourses { [weak self] result in
            switch result {
                
            case .success(let courses):
                self?.courses = courses
                let response = CourseList.ShowCourses.Response(courses: courses)
                self?.presenter?.presentCourses(response: response)
            case .failure(let error):
                print(error)
            }
        }
    }
}
